# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Svelte TypeScript CI

on:
  push:
    branches: [ "main", "feat/svelte-app" ]
  pull_request:
    branches: [ "main","feat/svelte-app" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm run test:ci

  e2e:
    runs-on: ubuntu-latest
    services:
      frequency-instant:
        image: "frequencychain/instant-seal-node:latest"
        ports:
          - "9944:9944" # ws and rpc port

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e
